### ISSUE TITLE
Update i2c-bus version

### ISSUE THREAD

**Issue by zazics** [101100/pca9685#17]
Hello,

This in already done in fork "https://github.com/fustaro/pca9685" but you should update your i2c-bus version to last one.
Otherwise it cause this error:
**_node_modules/pca9685/dist/src/pca9685.d.ts:1:10 - error TS2724: '"../../../@types/i2c-bus"' has no exported member named 'I2cBus'. Did you mean 'I2CBus'?**

**Comment by 101100** [comment]
Version 5.0.0 has been updated to all of the latest versions.
